#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/sctl
CONF=/etc/sctl/sctl.toml

start_service() {
	mkdir -p /etc/sctl
	mkdir -p /var/lib/sctl/sessions

	procd_open_instance
	procd_set_param command "$PROG" supervise --config "$CONF"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	:
}
